### ISSUE TITLE
[CONSOLE] Visualize Superfluid's networked flows

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/superfluid-console#107]
_To get started working on this bounty, follow these quick steps: https://docs.superfluid.finance/superfluid/resources/bounty-program_ 

## Synopsis
- Add a visualization tab to the Console, based on real data, of all flows and accounts on a given network.
    - The nodes should be individual accounts, displayed in short form e.g. 0xFFFF…FFFF
        - The addresses should be displayed with blockies identicons displayed next to the addresses
    - The interconnections between nodes should be flows
        - The flow rate, token symbol and token icons should be displayed next to them
- Links on flows and accounts should take me to the relevant console page.

## Context
As someone learning about Superfluid, I’d like a way to see the idea of interconnecting flows visualized so I can better understand the concepts involved.

- The visualization may use a library like [https://reactflow.dev/](https://reactflow.dev/)
- The solution should be implemented and opened in a PR against the Superfluid Console Github repository
- Implementing ENS resolution for addresses and profile pictures is not necessary but will be considered as a future extension of this feature.

Example:

![Image](https://user-images.githubusercontent.com/12459761/185140395-27bf81b3-0849-48bf-8399-6c8ac247a74f.png)

## Checklist
- [ ] New tab on Console (called e.g. Map)
- [ ] Visualization created which shows accounts and flows
- [ ] Blockies and shortened hex addresses are used
- [ ] Visualization shows real-time data
- [ ] Links to detailed Console pages for each stream and account

## Bounty reward
TBD

All our bounty payouts require a successful light KYC screening. See [Completion info](https://docs.superfluid.finance/superfluid/resources/bounty-program#upon-completion)

**Comment by Seroxdesign** [comment]
I would like to work on this.

**Comment by Seroxdesign** [comment]
@vmichalik @sunnyjaycer Is this available still?

**Comment by sunnyjaycer** [comment]
Hey @Seroxdesign, looks like it's open! Please follow these steps and you'll be all set to tackle this bounty:

https://docs.superfluid.finance/superfluid/resources/bounty-program 🚀

**Comment by Seroxdesign** [comment]
Hi @sunnyjaycer, I'm interested in taking on this bounty:
Expected Completion Date: 21st November

**Comment by AvinashNayak27** [comment]
Hey @sunnyjaycer is this bounty still open?

**Comment by vmichalik** [comment]
It's currently taken @AvinashNayak27 👍

**Comment by AvinashNayak27** [comment]
Thanks for the response👍

**Comment by AvinashNayak27** [comment]
Thanks for the response,it will be helpful if you can update the [ bounty list](https://github.com/orgs/superfluid-finance/projects/17/views/4) with available bounties

**Comment by Seroxdesign** [comment]
Bounty has been completed and is ready for review.

**Comment by elvijsTDL** [comment]
Done in #131
