### ISSUE TITLE
[CONSOLE] Add Matomo Analytics for Generic Visitor Data

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/superfluid-console#118]
- Tracking code to insert on each page can be found here
https://superfluidfinance.matomo.cloud/index.php?module=CoreAdminHome&action=trackingCodeGenerator&idSite=2&period=day&date=yesterday&updated=false
- Contact Vijay if Matomo login is needed

**Comment by tokdaniel** [comment]
I think this is a duplicate of https://app.zenhub.com/workspaces/user-products-team-61fba509b1fbfb00106daf63/issues/superfluid-finance/superfluid-console/47
