### ISSUE TITLE
[CONSOLE] show minimum deposit on token detail page

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/superfluid-console#161]
Tokens where minimum deposit is currently set:
* Ethereum: ETHx, USDCx, DAIx
* Polygon: AGOLD

When done, change https://docs.superfluid.finance/superfluid/sentinels/liquidations-and-toga#current-parameters to point to the console instead of hardcoding values. Also re-visit https://docs.superfluid.finance/superfluid/resources/superfluid-on-ethereum-mainnet.

**Comment by vmichalik** [comment]
```
query MyQuery {
  tokenGovernanceConfigs(first: 25) {
    minimumDeposit
    token {
      id
    }
  }
}





```
