### ISSUE TITLE
[CONSOLE] Refactor to use Metadata for Protocol Addresses

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/superfluid-console#173]
- Also expose additional missing contract addresses
  "resolver": 
            "host": 
            "governance":
            "cfaV1": 
            "cfaV1Forwarder": 
            "gdav1":
            "idaV1": 
            "superTokenFactory": 
            "superfluidLoader": 
            "toga": 
            "batchLiquidator": 
            "flowScheduler": 
            "vestingScheduler": 
         
      
Recommendation by @kasparkallas has been to use a packaged publication of the protocol metadata
Blocked by https://github.com/superfluid-finance/metadata/issues/31

**Comment by kasparkallas** [comment]
* Possibly include Subgraph URLs as well for the peripheral contracts (vesting, auto-wrap, scheduling).
* We also keep a list of Superfluid RPCs in the dApps that could be offloaded to the metadata.
