### ISSUE TITLE
[CONSOLE] Add support for GDA Features

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/superfluid-console#183]
- [x] there is an indexes tab on the token page (and maybe elsewhere)
- [x] in the GDA, an index is called a pool
- [x] instead of a publisher, you have the admin
- [x] the total distributed field is static for IDA, but it MAY be dynamic for GDA if there is a flow rate
- [x] on the index page/modal you have: token, publisher, index id. for the gda, you will have token, admin and pool address (organize accordingly)
- [x] you also have the concept of total units, total units approved and total units pending (this is effectively the same)
- [x] there is also a table of distributions which the GDA will contain, but there were also be flow distributions/flow distribution updates
- [x] there is a table of subscriptions, this would be a table of pool members in the GDA

**Comment by kasparkallas** [comment]
No designs are coming up. Developers are free to implement in the Console.

**Comment by msoni89** [comment]
https://github.com/superfluid-finance/superfluid-console/pull/190/files

**Comment by msoni89** [comment]
https://superfluidhq.slack.com/archives/CTWKJ8TEH/p1695145270168299

**Comment by philipandersson** [comment]
@d10r Can proceed with testing? Is the data correct?

**Comment by elvijsTDL** [comment]
Been out there for a while now #190
