### ISSUE TITLE
[CONSOLE] Change Network from Account Page

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/superfluid-console#31]
### Problem

- As a user I’d like to quickly be able to navigate from an account on one chain to the same account on a different chain without having to re-enter search

### Solution

- Chevron and MUI drop-down box on network name for selecting address page on other networks
- Custom query to determine the networks an address has been interacted with on

### Notes

**Comment by kasparkallas** [comment]
Solved here: https://github.com/superfluid-finance/superfluid-console/issues/31
