### ISSUE TITLE
[CONSOLE] Determine number of users and queries

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/superfluid-console#47]
**Problem**
- In order to determine if the Console is gaining traction, we should track the number of visitors and the usage. 
- This doesn't require us to track or process any further details at this time, but it should follow the pattern of our existing segment and mixpanel setup and not create conflicts.

To track:
- Number of unique users
- Number of page visits per user

**Solution**
- Potentially using Segment and Mixpanel

**Comment by kasparkallas** [comment]
We could use Matomo: https://matomo.org/
