### ISSUE TITLE
[CONSOLE] ENS Support

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/superfluid-console#58]
**User Need**
- ENS Forward Lookup for searches
- ENS Reverse Lookup for resolving hex addresses to ENS names

**Solution**
- Look into ENS team state of the art recommendations
- Use RPC or Subgraph
- May require a mainnet Ethereum RPC

**Rabbitholes**
- We might want to consider ENS avatar support down the line
- If address is a contract, it could cause issues for users initiating streams on L2s where that contract is not deployed (smart contract wallets etc)

**Comment by kasparkallas** [comment]
Solved here: https://github.com/superfluid-finance/superfluid-console/pull/105
