### ISSUE TITLE
[CONSOLE] Cypress test cases for filtering

### ISSUE THREAD

**Issue by elvijsTDL** [superfluid-finance/superfluid-console#63]
Filtering test cases:

Filtering common cases:
- [x] Filtering window - close button
- [x] Filtering window - reset button
- [x] Filtering window - clearing text input with the "x" button by the input
- [x] Filtering window - clearing filters with the "x" button by the filter chip
- [x] Filtering - no data found

Account incoming streams table
- [x] Filtering by sender address
- [x] Filtering by Active/Inactive 

Account outgoing streams table
- [x] Filtering by receiver address
- [x] Filtering by Active/Inactive

Account index publications table
- [x] Filtering by index id
- [x] Filtering by distributions happened or not
- [x] Filtering by units issues or not
- [x] Reseting the filter shows the data that was shown previously

Account index subscriptions table
- [x] Filtering by approved/not approved
- [x] Filtering by having/not having received a distribution
- [x] Filtering by units issued

Account super tokens table
- [x] Filtering by active streams
- [x] Filtering by closed streams
- [x] Filtering by subscriptions

Events table
- [x] Filtering by event name
- [x] Filtering by block number
- [x] Filtering by tx hash

Super token streams table
- [x] Filtering by sender address
- [x] Filtering by receiver address
- [x] Filtering by active/inactive streams

Super token indexes table
- [x] Filtering by index id 
- [x] Filtering by publisher address
- [x] Filtering by distributions have/haven't happened

Other:
- [x] Super token page - validate token overall data
- [x] Account page - validate that new balances in account page are shown correctly
- [x] Subgraph address getting switched to lowercase toast message
- [x] Add arbitrum-one and opitmism-mainnet to network smoke test
- [x] Regular tokens show 404 instead of a broken page

**Comment by vmichalik** [comment]
@elvijsTDL is this all done? just cleaning up

**Comment by elvijsTDL** [comment]
Done, but not merged @kasparkallas Can you review it https://github.com/superfluid-finance/superfluid-console/pull/79
