### ISSUE TITLE
[CONSOLE] Add support for ENS domains

### ISSUE THREAD

**Issue by developerfred** [superfluid-finance/superfluid-console#87]
### Synopsis

As a Console user, I'd like to be able to use human-readable addresses in the Console.

### Context

This includes:
- Forward resolution in search from ENS name to Hex Address
- Reverse resolution on address pages from Hex Address to ENS

### Checklist

- [ ] Use RTK-Query for caching and request de-duplication. NOTE: There is a redux slice for this in the new dashboard. See comment below [1]
- [ ] Resolve "reverse resolution" correctly/safely: https://docs.ens.domains/dapp-developer-guide/resolving-names#reverse-resolution. NOTE: This should be straightforward with ethers.js
- [ ] Handle UI for account having both address book name and ENS name.

### Acceptance Criteria
* Users can search by ENS name in the search bar and see results
* Users can see ENS names resolved on address pages
* The solution is safe and correct.
* The solution doesn't overly spam RPC-s / Subgraph.
* Passes a subjective code review for quality by the Supefluid Finance team.

### Additional References
Any solution should take account of the ENS front-end design guidelines https://docs.ens.domains/dapp-developer-guide/front-end-design-guidelines
https://www.npmjs.com/package/@ensdomains/ens-contracts

Future work:
- Reverse resolution in Latest Streams, Account , Super Token, Streams, Index and Index Subscription pages.

### Bounty Reward:
$250 paid in stablecoin on Polygon
Bounty Program info: https://docs.superfluid.finance/superfluid/resources/bounty-program

**Comment by vmichalik** [comment]
Thanks for opening an issue @developerfred!
Which areas are you most interested in having ENS support in the console?
Is it something you'd be interested in contributing?

**Comment by developerfred** [comment]
@vmichalik I thought about adding the ens resolver for search and viewing in the address book, yes I want to contribute.

**Comment by kasparkallas** [comment]
Some possible points for the checklist:

- [ ] Use RTK-Query for caching and request de-duplication. NOTE: I did a redux slice for this in the new dashboard. [1]
- [ ] Resolve "reverse resolution" correctly/safely: https://docs.ens.domains/dapp-developer-guide/resolving-names#reverse-resolution. NOTE: In the new dashboard, I used ethers.js which handles this itself.
- [ ] Handle UI for account having both address book name and ENS name.

When doing ENS lookups for list views:
- [ ] Handle querying ENS names when there's 50 addresses visible in a table. NOTE: I don't know how to best do this yet. Probably would have to query the names from Subgraph in one go somehow. 

More optional extensions:
- Use ENS avatar for account page

Acceptance Criterias?
* The solution is safe and correct.
* The solution doesn't overly spam RPC-s / Subgraph.
* Passes a subjective code review for quality by the Supefluid Finance team.

Other acceptance criterias are from user's perspective (i.e. user can search by ENS name) which someone else can spec. I didn't put an acceptance criteria for tests because we don't have unit tests and the E2E tests are probably best written by our QA team.



[1] Redux slice for ENS lookups using ethers:
```ts
import { fakeBaseQuery } from "@reduxjs/toolkit/dist/query";
import { createApi } from "@reduxjs/toolkit/dist/query/react";
import { ethers } from "ethers";

export const ensApi = createApi({
  reducerPath: "ens",
  baseQuery: fakeBaseQuery(),
  endpoints: (builder) => {
    const mainnetProvider = new ethers.providers.InfuraProvider(
      "mainnet",
      "INFURA_KEY"
    );

    return {
      resolveName: builder.query<
        { address: string; name: string } | null,
        string
      >({
        queryFn: async (name) => {
          if (ethers.utils.isAddress(name)) {
            return { data: null };
          }

          const address = await mainnetProvider.resolveName(name);
          return {
            data: address
              ? {
                  name,
                  address: address,
                }
              : null,
          };
        },
      }),
      lookupAddress: builder.query<
        { address: string; name: string } | null,
        string
      >({
        queryFn: async (address) => {
          const name = await mainnetProvider.lookupAddress(address);
          return {
            data: name
              ? {
                  name,
                  address: ethers.utils.getAddress(address),
                }
              : null,
          };
        },
      }),
    };
  },
});

```

**Comment by sunnyjaycer** [comment]
Hey @developerfred! I'm attaching a small bounty to this work, just to reward you upon completion. Thank you for stepping up here!

For info on claiming the bounty on completion, see here: https://docs.superfluid.finance/superfluid/resources/bounty-program

**Comment by developerfred** [comment]
@kasparkallas

Today there is rss3 feed, it has a base with thousands of consumers and ENS, it has a subgraph and stores it in a bank. There is a public direct response api:


https://rss3.domains/name/:id

on here
https://rss3.domains/name/codingsh.eth

**Comment by developerfred** [comment]
@kasparkallas I have a question about how redux automatically generates hooks in my build is not generating.

**Comment by developerfred** [comment]
I supported both rss3 and ethers requests

**Comment by developerfred** [comment]
<img width="1085" alt="Screenshot 2022-05-26 at 02 40 23" src="https://user-images.githubusercontent.com/57037080/170397894-a276c789-f865-46e9-b11a-8e07843d7b09.png">

**Comment by vmichalik** [comment]
Hey @developerfred, looking awesome!
I would probably switch around the order here a little, as you've currently got ENS as a button which implies it's clickable.
I'd put it on the same line just after the hex address in a subtitle font. That's the slightly darker grey colour in dark mode per the subtitles below.

**Comment by Seroxdesign** [comment]
## On typing either the ENS or Wallet address:

![Image](https://user-images.githubusercontent.com/69639595/177057347-49327c5a-2b39-4d10-b8e1-2a1029574f2a.png)

## When viewing a specific account with an ENS

![Image](https://user-images.githubusercontent.com/69639595/177057494-d80ea7a0-02af-45bf-8868-acb1f7d51e96.png)

I wanted to get people's opinions on the UI before I start implementation.

**Comment by vmichalik** [comment]
Thanks @Seroxdesign, I sent a message on Discord with some additional context, but excited to see your work on this!
